name: Build and Deploy Code

on: [push, pull_request]

jobs: 
    job1:
        env:
          DATABASE_HOSTNAME: localhost
          DATABASE_PORT: 5432
          DATABASE_PASSWORD: DataBas3!#
          DATABASE_NAME: fastapi
          DATABASE_USERNAME: postgres
          SECRET_KEY: 09d25e094faa6ca2556c828266b7a9563b93f7099f63b88e8d3e7
          ALGORITHM: HS256
          ACCESS_TOKEN_EXPIRE_MINUTES: 60
        runs-on: ubuntu-latest
        steps:
          - name: pulling git repo
            uses: actions/checkout@v3.5.3
          - name: install python version 3.9
            uses: actions/setup-python@v2
            with:
              python-version: "3.9"
          - name: upgrade pip
            run: python -m pip install --upgrade pip
          - name: install all dependeces
            run: pip install -r requirements.txt
          - name: test with pytest
            run: |
              pip install pytest
              pytest